<?php 
return [
		
'site_title' => 'Laravel Demo',
'CaptchaSiteKey' => '6Ld9HjwUAAAAAPjcRL7Vl00rQ5LbtiUhf4GZS21o',
'CaptchaSecretKey' => '6Ld9HjwUAAAAAD3Kv8GvUjH_T6wyNS7acSekMTp9',
'dateFormat' => 'Y-m-d',
'dateTimeFormat' => 'Y-m-d h:m:s',
'isClientValidationStop' => 0,
'isClientValidationStop_admin' => 0,
'fromEmailName' => 'Fondae',
'checkCaptcha' => 0,
'sendEmail' => 0,
'developerEmail' => 0,
'background_home' => 'Winter.jpg',
'image' => '<p>ghfghfhfghfgh</p>',
'copyright' => '© Copyright 2017 by Fondae. All rights reserved.',
'contact' => ' +1-800-935-3714 ',
'paginationLink' => 3,
'contactusFormID' => 1,
'enewsletterFormID' => 2,
'eventFormID' => 3,
'newsCategorytypeID' => 1,
'faqCategorytypeID' => 2,
'productCategorytypeID' => 3,
'linkCategorytypeID' => 4,
'portfolioCategorytypeID' => 5,
'eventCategorytypeID' => 6,
'contactCategorytypeID' => 7,
'servicesCategorytypeID' => 8,
'staffCategorytypeID' => 10,

'newsImageTypeID' => 2,
'productImageTypeID' => 4,
'eventImageTypeID' => 5,
'serviceImageTypeID' => 7,
'galleryImageTypeID' => 6,
'portfolioImageTypeID' => 3,
'newsFileTypeID' => 2,
'config_mandatory_field' => '<span class="required_star">*</span>',
'contactEmail' => 'cs@fondae.com',
'contactTitle' => 'D9ITHUB',
'contactAddress' => '<p>250 Elizabeth , NY, US					   </p>',
'contactMap' => '<iframe src="https://www.google.com/maps/embed?" style="border:0" width="100%" height="330" frameborder="0">
</iframe>',
'contactNumber' => ' +1-800-935-3714 ',
'tooltips' => 'Your password needs to contain minimum 6 digit ',
'checkMailContent' => 0,
'showError' => 0,
'errorEmail' => 0,
'priceClass' => 'fa fa-usd',
'fromEmail' => 'parth.d9ithub@gmail.com',
'productPriceCategorytypeID' => 9,
'Tax' => 14,
'priceSign' => '$',
'customerFormID' => 4,
'orderFormID' => 5,
'forgotpasswordFormID' => 9,
'resetpasswordFormID' => 10,
'guestCustomerType' => 2,
'packageCategorytypeID' => 12,
'developed_title' => 'd9ithub.com',
'developed_site' => 'https://www.d9ithub.com/',
'stripeSecret' => 'sk_test_JHkeSk0TcHyltgBvCTfDD9f2',
'stripePublishable' => 'pk_test_upEu5iwxVb6G3IDSxoltWasv',

		 
] ?>