<?php 
return [
		
'site_title' => 'Laravel Demo',
'fe_url' => '/projects/hrcms/www/',
'fck_url' => 'http://phpserver4/projects/hrcms/www/',
'CaptchaSiteKey' => '6LcOIQgTAAAAAE4LByXdCPEctJhJv2OZKhdKTVew',
'CaptchaSecretKey' => '6LcOIQgTAAAAAEar9IjMLD6Lb6GEqKBMENjdz_Db',
'dateFormat' => 'Y-m-d',
'dateTimeFormat' => 'Y-m-d h:m:s',
'isClientValidationStop' => 0,
'fromEmail' => 'patelpriyank1984@gmail.com',
'fromEmailName' => 'HR CMS',
'checkCaptcha' => 0,
'sendEmail' => 0,
'developerEmail' => 0,
'background_home' => 'Winter.jpg',
'image' => '<p>ghfghfhfghfgh</p>',
'copyright' => '© 2015 preferred printing & graphics',
'contact' => '079 - 22741110',
'paginationLink' => 3,
'contactusFormID' => 1,
'enewsletterFormID' => 2,
'emailthispageFormID' => 3,
'newsCategorytypeID' => 1,
'faqCategorytypeID' => 2,
'productCategorytypeID' => 3,
'linkCategorytypeID' => 4,
'portfolioCategorytypeID' => 5,
'eventCategorytypeID' => 6,
'contactCategorytypeID' => 7,
'servicesCategorytypeID' => 8,
'staffCategorytypeID' => 9,
'newsImageTypeID' => 2,
'productImageTypeID' => 4,
'eventImageTypeID' => 5,
'serviceImageTypeID' => 7,
'galleryImageTypeID' => 6,
'portfolioImageTypeID' => 3,
'newsFileTypeID' => 2,
'config_mandatory_field' => '<span class="required_star">*</span>',

		 
] ?>